"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, Building2, FileCheck2, FileText, MailCheck, Send, Sparkles, Users } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { Badge, Card, PageHeader, Spinner } from "@/components/ui";

type Data = { stats: Record<string,number>; categories:Array<{name:string;value:number}>; priority:Array<any>; logs:Array<any> };
const colors=["#6d5dfc","#3b82f6","#14b8a6","#f59e0b","#ec4899","#64748b"];
const cards=[ ["Total HR contacts","contacts",Users],["Unique companies","companies",Building2],["Companies researched","researched",Sparkles],["Emails generated","emails",FileText],["Resumes generated","resumes",FileCheck2],["Drafts created","drafts",MailCheck],["Emails sent","sent",Send],["Manual review","review",AlertTriangle] ] as const;
export default function DashboardPage(){const[data,setData]=useState<Data>();useEffect(()=>{fetch("/api/dashboard").then(r=>r.json()).then(setData)},[]);if(!data)return <div className="grid h-80 place-items-center text-violet-600"><Spinner/></div>;return <><PageHeader title="Outreach command center" description="Every contact, artifact, approval, and delivery at a glance."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,key,Icon])=><Card key={key} className="p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Icon size={19}/></span>{key==="review"&&data.stats[key]>0?<Badge tone="yellow">Needs attention</Badge>:<span className="text-xs text-gray-400">All time</span>}</div><strong className="mt-5 block text-3xl">{data.stats[key]||0}</strong><span className="mt-1 block text-sm text-gray-500">{label}</span></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-6"><h2 className="font-bold">Company categories</h2><p className="mt-1 text-sm text-gray-500">Distribution across researched companies</p><div className="mt-4 h-64">{data.categories.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.categories} dataKey="value" nameKey="name" innerRadius={55} outerRadius={88} paddingAngle={3}>{data.categories.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-gray-400">Research companies to see the mix.</div>}</div></Card><Card className="overflow-hidden"><div className="p-6"><h2 className="font-bold">Priority companies</h2><p className="mt-1 text-sm text-gray-500">Highest-scoring opportunities first</p></div><div className="table-wrap"><table><thead><tr><th>Company</th><th>Category</th><th>Score</th><th>Confidence</th></tr></thead><tbody>{data.priority.map(c=><tr key={c.id}><td><strong>{c.companyName}</strong><small className="block text-gray-400">{c.hrEmail}</small></td><td><Badge tone="blue">{c.research?.category||"Unresearched"}</Badge></td><td><strong>{c.priorityScore}</strong><small className="block text-gray-400">{c.hiringLikelihood}</small></td><td>{c.research?.confidenceScore??"—"}%</td></tr>)}</tbody></table></div></Card></div><Card className="mt-6 overflow-hidden"><div className="p-6"><h2 className="font-bold">Recent activity</h2></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Company</th><th>Status</th><th>Message</th></tr></thead><tbody>{data.logs.map(l=><tr key={l.id}><td>{new Date(l.createdAt).toLocaleString()}</td><td>{l.action.replaceAll("_"," ")}</td><td>{l.companyName||l.campaign?.name||"—"}</td><td><Badge tone={l.status==="SUCCESS"?"green":l.status==="FAILED"?"red":"yellow"}>{l.status}</Badge></td><td className="max-w-md truncate text-gray-500">{l.message}</td></tr>)}</tbody></table></div></Card></>}
