import Link from "next/link";
import { ArrowRight, CheckCircle2, FileSearch, MailCheck, ShieldCheck, Sparkles, Upload } from "lucide-react";

export default function Landing() { return <main className="min-h-screen bg-[#0c1020] text-white">
  <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><div className="flex items-center gap-2 text-xl font-bold"><span className="grid size-9 place-items-center rounded-xl bg-violet-500"><Sparkles size={18}/></span>ColdMailOS</div><Link className="btn border border-white/15 bg-white/5 text-white hover:bg-white/10" href="/dashboard">Go to Dashboard <ArrowRight size={16}/></Link></nav>
  <section className="mx-auto grid max-w-6xl gap-14 px-6 pb-24 pt-20 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div><div className="mb-5 inline-flex rounded-full border border-violet-400/30 bg-violet-400/10 px-3 py-1 text-sm text-violet-200">Personalized outreach without the reckless bits</div><h1 className="max-w-3xl text-5xl font-bold leading-[1.05] tracking-tight sm:text-6xl">Turn an HR spreadsheet into thoughtful, reviewable outreach.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">ColdMailOS researches each company, tailors Om’s résumé, drafts a grounded email, and keeps a human firmly on the send button.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/upload" className="btn btn-primary px-5 py-3">Start a campaign <ArrowRight size={17}/></Link><Link href="/single" className="btn border border-white/15 bg-white/5 px-5 py-3 text-white">Single company mode</Link></div></div>
  <div className="rounded-3xl border border-white/10 bg-white/[.06] p-5 shadow-2xl"><div className="rounded-2xl bg-[#f8f9fc] p-5 text-gray-900"><div className="mb-5 flex items-center justify-between"><strong>Campaign pipeline</strong><span className="badge bg-emerald-50 text-emerald-700">8 ready for review</span></div>{[["Upload contacts","142 rows",Upload],["Company research","128 verified",FileSearch],["Personalized assets","118 generated",Sparkles],["Gmail drafts","64 approved",MailCheck]].map(([a,b,Icon])=><div key={String(a)} className="mb-3 flex items-center gap-3 rounded-xl border border-gray-200 bg-white p-4"><span className="grid size-10 place-items-center rounded-lg bg-violet-50 text-violet-700"><Icon size={19}/></span><span className="flex-1"><strong className="block text-sm">{a as string}</strong><small className="text-gray-500">{b as string}</small></span><CheckCircle2 size={19} className="text-emerald-500"/></div>)}</div></div></section>
  <section className="border-t border-white/10 bg-white/[.03]"><div className="mx-auto grid max-w-6xl gap-5 px-6 py-20 md:grid-cols-3">{[["Deep, cited research","Tavily evidence is summarized with sources and confidence—low-confidence rows stop for review."],["One résumé per company","Every contact gets an immutable, company-matched PDF. The original source stays untouched."],["No accidental blasts","Draft-first defaults, explicit approval, typed confirmation, rate limits, and individual sends only."]].map(([h,p],i)=><div key={h} className="rounded-2xl border border-white/10 bg-white/5 p-6"><span className="mb-5 grid size-10 place-items-center rounded-xl bg-violet-500/20 text-violet-300">{i===2?<ShieldCheck/>:<Sparkles/>}</span><h2 className="text-lg font-bold">{h}</h2><p className="mt-2 leading-7 text-slate-400">{p}</p></div>)}</div></section>
</main>; }
