"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createColumnHelper, flexRender, getCoreRowModel, getFilteredRowModel, useReactTable } from "@tanstack/react-table";
import { AlertTriangle, Check, Eye, FileText, Mail, Search, Send, Sparkles, X, Zap } from "lucide-react";
import { Badge, Button, Card, Spinner } from "@/components/ui";

const tone=(status:string)=>status==="SENT"||status==="APPROVED"?"green":status==="DRAFTED"?"teal":status==="FAILED"?"red":status==="MANUAL_REVIEW"?"yellow":status==="GENERATED"?"purple":status==="RESEARCHED"?"blue":"gray";
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-gray-950/50 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-5"><h2 className="font-bold">{title}</h2><button onClick={onClose}><X size={20}/></button></div><div className="p-6">{children}</div></div></div>}

export function CampaignTable({campaign}:{campaign:any}){const router=useRouter();const[selection,setSelection]=useState({});const[filter,setFilter]=useState("");const[busy,setBusy]=useState("");const[progress,setProgress]=useState("");const[modal,setModal]=useState<any>();const[confirm,setConfirm]=useState("");const helper=createColumnHelper<any>();
  const[automation,setAutomation]=useState<any>();
  useEffect(()=>{let timer:ReturnType<typeof setInterval>|undefined;async function check(){try{const r=await fetch(`/api/campaigns/${campaign.id}/automate`,{cache:"no-store"});if(!r.ok)return;const data=await r.json();setAutomation(data);if(data.active>0)router.refresh();else if(timer){clearInterval(timer);timer=undefined;router.refresh()}}catch{}}timer=setInterval(check,5000);check();return()=>{if(timer)clearInterval(timer)}},[campaign.id,router]);
  const columns=useMemo(()=>[
    helper.display({id:"select",header:({table})=><input type="checkbox" checked={table.getIsAllPageRowsSelected()} onChange={table.getToggleAllPageRowsSelectedHandler()}/>,cell:({row})=><input type="checkbox" checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()}/>}),
    helper.accessor("status",{header:"Status",cell:i=><Badge tone={tone(i.getValue())}>{String(i.getValue()).replaceAll("_"," ")}</Badge>}),
    helper.accessor("hrName",{header:"HR contact",cell:i=><div><strong>{i.getValue()||"Hiring Team"}</strong><small className="block text-gray-400">{i.row.original.hrEmail}</small></div>}),
    helper.accessor("companyName",{header:"Company",cell:i=><strong>{i.getValue()}</strong>}),
    helper.accessor("research.category",{header:"Category",cell:i=><span>{i.getValue()||"—"}</span>}),
    helper.accessor("priorityScore",{header:"Priority",cell:i=><div><strong>{i.getValue()}</strong><small className="block text-gray-400">{i.row.original.hiringLikelihood}</small></div>}),
    helper.accessor("research.confidenceScore",{header:"Confidence",cell:i=><span>{i.getValue()??"—"}{i.getValue()!=null&&"%"}</span>}),
    helper.display({id:"assets",header:"Artifacts",cell:({row})=><div className="flex gap-1"><Badge tone={row.original.generatedResumes[0]?.compileStatus==="COMPLETED"?"purple":"gray"}>Resume</Badge><Badge tone={row.original.generatedEmails[0]?"purple":"gray"}>Email</Badge></div>}),
    helper.display({id:"delivery",header:"Delivery",cell:({row})=><Badge tone={row.original.sentEmails[0]?"green":row.original.gmailDrafts[0]?"teal":"gray"}>{row.original.sentEmails[0]?"Sent":row.original.gmailDrafts[0]?"Draft Created":"Not drafted"}</Badge>}),
    helper.display({id:"review",header:"Review",cell:({row})=>{const needed=(row.original.research?.manualReviewRequired||row.original.generatedEmails[0]?.manualReviewRequired)&&!row.original.manualReviewResolved;return needed?<Badge tone="yellow"><AlertTriangle size={12}/> Required</Badge>:<Badge tone="green">Clear</Badge>}}),
    helper.display({id:"actions",header:"Actions",cell:({row})=><select className="input !w-40 !py-2 text-xs" value="" disabled={busy===row.original.id+"automate"} onChange={e=>{action(row.original,e.target.value);e.currentTarget.value=""}}><option value="">Choose action…</option><option value="automate">Run automation</option><option value="viewResearch" disabled={!row.original.research}>View / edit research</option><option value="previewResume" disabled={!row.original.generatedResumes[0]?.pdfFileUrl}>Preview resume</option><option value="viewEmail" disabled={!row.original.generatedEmails[0]}>Review & approve email</option><option value="draft" disabled={!row.original.generatedEmails[0]?.approved}>Create draft</option><option value="send">Send email</option><option value="review">Mark reviewed</option><option value="skip">Skip contact</option></select>}),
  ],[]);
  const table=useReactTable({data:campaign.contacts,columns,state:{rowSelection:selection,globalFilter:filter},onRowSelectionChange:setSelection,onGlobalFilterChange:setFilter,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getRowId:r=>r.id});
  const selected=table.getSelectedRowModel().rows.map(r=>r.original);
  async function call(url:string,body?:any){const r=await fetch(url,{method:"POST",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
  async function one(row:any,type:string){setBusy(row.id+type);try{if(type==="automate"){const queued=await call(`/api/campaigns/${campaign.id}/automate`,{contactIds:[row.id]});setAutomation({active:queued.queued,pending:queued.queued,processing:0,completed:0,failed:0})}if(type==="draft")await call(`/api/contacts/${row.id}/create-draft`);if(type==="review"||type==="skip"){const r=await fetch(`/api/contacts/${row.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:type})});if(!r.ok)throw new Error((await r.json()).error)}router.refresh()}catch(e){setModal({error:e instanceof Error?e.message:"Action failed"})}finally{setBusy("")}}
  function action(row:any,type:string){if(type==="viewResearch")setModal({research:row.research,row});else if(type==="previewResume")window.open(`/api/resumes/generated/${row.generatedResumes[0]?.id}/pdf`,"_blank","noopener,noreferrer");else if(type==="viewEmail")setModal({email:row.generatedEmails[0],row});else if(type==="send"){setConfirm("");setModal({send:[row]})}else if(type)one(row,type)}
  async function automate(){setBusy("automate");setProgress("Queuing contacts…");try{const queued=await call(`/api/campaigns/${campaign.id}/automate`,selected.length?{contactIds:selected.map(row=>row.id)}:{});setAutomation({active:queued.queued,pending:queued.queued,processing:0,completed:0,failed:0});setProgress(`${queued.queued} contact${queued.queued===1?"":"s"} queued`);setSelection({});router.refresh()}catch(e){setModal({error:e instanceof Error?e.message:"Automation failed"})}finally{setBusy("")}}
  async function approve(email:any,row:any){setBusy("approve");try{await call(`/api/contacts/${row.id}/approve-email`,{approved:true,subject:email.subject,body:email.body,resolveManualReview:true});await call(`/api/contacts/${row.id}/create-draft`);setModal(undefined);router.refresh()}catch(e){setModal({error:e instanceof Error?e.message:"Email was approved, but Gmail draft creation needs attention: "+String(e)})}finally{setBusy("")}}
  async function saveResearch(research:any,row:any){setBusy("researchEdit");try{const r=await fetch(`/api/contacts/${row.id}/research`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...research,resolveManualReview:true})});const d=await r.json();if(!r.ok)throw new Error(d.error);setModal(undefined);await one(row,"automate");router.refresh()}catch(e){setModal({error:e instanceof Error?e.message:"Research update failed"})}finally{setBusy("")}}
  async function send(){const rows=modal.send as any[];setBusy("send");try{await call(`/api/campaigns/${campaign.id}/send-approved`,{contactIds:rows.map(r=>r.id),confirm});setModal(undefined);router.refresh()}catch(e){setModal({error:e instanceof Error?e.message:"Send failed"})}finally{setBusy("")}}
  const visibleRows=table.getRowModel().rows;
  return <><Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:flex-wrap sm:items-center"><div className="relative min-w-0 flex-1 sm:min-w-64"><Search className="absolute left-3 top-2.5 text-gray-400" size={17}/><input className="input !py-2 pl-9" placeholder="Filter contacts or companies…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><span className="text-xs text-gray-500">{selected.length?`${selected.length} selected`:"No selection runs all pending contacts"}</span><Button onClick={automate} disabled={!!busy||Boolean(automation?.active)}><Zap size={15}/> {selected.length?"Automate selected":"Automate pending"}</Button><Button variant="danger" onClick={()=>{setConfirm("");setModal({send:selected.filter(r=>r.generatedEmails[0]?.approved)})}} disabled={!selected.some(r=>r.generatedEmails[0]?.approved)||!!busy}><Send size={15}/> Send approved</Button></div>{(busy||automation?.active>0)&&<div className="flex flex-wrap items-center gap-2 bg-violet-50 px-5 py-3 text-sm text-violet-700"><Spinner/> Automation running in the background · {automation?.completed||0} complete · {(automation?.pending||0)+(automation?.processing||0)} remaining {progress&&`· ${progress}`}</div>}{automation?.active===0&&automation?.failed>0&&<div className="border-t border-red-200 bg-red-50 px-5 py-4 text-sm text-red-800"><div className="flex items-start gap-2"><AlertTriangle className="mt-0.5 shrink-0" size={17}/><div><strong>Automation paused after {automation.failed} failed job{automation.failed===1?"":"s"}.</strong><p className="mt-1">{automation.recentFailures?.[0]?.message||"Open Activity Logs for the exact provider error."}</p>{automation.recentFailures?.[0]?.code==="GEMINI_SPEND_CAP"&&<a className="mt-2 inline-block font-semibold underline" href="https://ai.studio/spend" target="_blank" rel="noreferrer">Manage Gemini spending cap</a>}</div></div></div>}
  <div className="space-y-3 p-3 md:hidden">{visibleRows.map(({original:row})=>{const checked=selected.some(item=>item.id===row.id);return <article key={row.id} className="rounded-xl border p-4"><div className="flex items-start gap-3"><input className="mt-1" type="checkbox" checked={checked} onChange={()=>table.getRow(row.id).toggleSelected()} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="truncate">{row.companyName}</strong><Badge tone={tone(row.status)}>{String(row.status).replaceAll("_"," ")}</Badge></div><p className="mt-1 truncate text-sm text-gray-500">{row.hrName||"Hiring Team"} · {row.hrEmail}</p><div className="mt-3 flex flex-wrap gap-2"><Badge tone={row.generatedResumes[0]?.compileStatus==="COMPLETED"?"purple":"gray"}>Resume</Badge><Badge tone={row.generatedEmails[0]?"purple":"gray"}>Email</Badge>{row.gmailDrafts[0]&&<Badge tone="teal">Draft</Badge>}</div><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" className="!px-3 !py-2 text-xs" onClick={()=>one(row,"automate")} disabled={!!busy}><Zap size={14}/> Automate</Button>{row.generatedResumes[0]?.pdfFileUrl&&<Button variant="secondary" className="!px-3 !py-2 text-xs" onClick={()=>action(row,"previewResume")}><Eye size={14}/> PDF</Button>}{row.generatedEmails[0]&&<Button variant="secondary" className="!px-3 !py-2 text-xs" onClick={()=>action(row,"viewEmail")}><Mail size={14}/> Review</Button>}</div></div></div></article>})}</div>
  <div className="table-wrap hidden md:block"><table><thead>{table.getHeaderGroups().map(hg=><tr key={hg.id}>{hg.headers.map(h=><th key={h.id}>{h.isPlaceholder?null:flexRender(h.column.columnDef.header,h.getContext())}</th>)}</tr>)}</thead><tbody>{visibleRows.map(row=><tr key={row.id} className={row.getIsSelected()?"bg-violet-50/40":""}>{row.getVisibleCells().map(cell=><td key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table></div></Card>
  {modal?.research&&<ResearchModal research={modal.research} row={modal.row} busy={busy} onClose={()=>setModal(undefined)} onSave={saveResearch}/>} 
  {modal?.email&&<EmailModal email={modal.email} row={modal.row} busy={busy} onClose={()=>setModal(undefined)} onApprove={approve}/>} 
  {modal?.send&&<Modal title="Final send confirmation" onClose={()=>setModal(undefined)}><div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><strong>{modal.send.length} separate email{modal.send.length===1?"":"s"}</strong> will be queued. Each uses its own recipient, body, and matched résumé. No CC or BCC is used.</div><ul className="mt-4 max-h-48 space-y-2 overflow-auto text-sm">{modal.send.map((r:any)=><li key={r.id} className="flex justify-between rounded-lg bg-gray-50 p-3"><span>{r.companyName}</span><span className="text-gray-500">{r.hrEmail}</span></li>)}</ul><label className="label mt-5">Type CONFIRM</label><input className="input" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="CONFIRM"/><div className="mt-5 flex justify-end gap-3"><Button variant="secondary" onClick={()=>setModal(undefined)}>Cancel</Button><Button variant="danger" disabled={confirm!=="CONFIRM"||busy==="send"} onClick={send}>{busy==="send"?<Spinner/>:<Send size={16}/>} Queue individual sends</Button></div></Modal>}
  {modal?.error&&<Modal title="Action needs attention" onClose={()=>setModal(undefined)}><p className="whitespace-pre-wrap rounded-xl bg-red-50 p-4 text-sm leading-6 text-red-700">{modal.error}</p></Modal>}</>}

function EmailModal({email,row,busy,onClose,onApprove}:{email:any;row:any;busy:string;onClose:()=>void;onApprove:(e:any,r:any)=>void}){const[draft,setDraft]=useState({...email});const[confirmed,setConfirmed]=useState(false);return <Modal title={`Review email · ${row.companyName}`} onClose={onClose}><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Recipient</label><input className="input bg-gray-50" readOnly value={row.hrEmail}/></div><div><label className="label">Resume attachment</label><input className="input bg-gray-50" readOnly value={row.generatedResumes[0]?.fileName||"Missing — generation required"}/></div></div>{(row.research?.manualReviewRequired||email.manualReviewRequired)&&!row.manualReviewResolved&&<div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-800"><AlertTriangle className="mr-2 inline" size={16}/>This item requires manual review. Approving it here records the resolution.</div>}<div className="mt-4"><label className="label">Subject</label><input className="input" value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})}/></div><div className="mt-4"><label className="label">Email body</label><textarea className="input min-h-80 leading-6" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></div><label className="mt-4 flex items-start gap-3 rounded-xl border bg-gray-50 p-4 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I verified the recipient, company claims, email copy, and attached résumé.</span></label><div className="mt-5 flex items-center justify-between"><span className="text-sm text-gray-500">Confidence: {email.confidenceScore}% · {draft.body.trim().split(/\s+/).length} words</span><Button onClick={()=>onApprove(draft,row)} disabled={!confirmed||busy==="approve"}>{busy==="approve"?<Spinner/>:<Check size={16}/>} Save & approve</Button></div></Modal>}

function ResearchModal({research,row,busy,onClose,onSave}:{research:any;row:any;busy:string;onClose:()=>void;onSave:(r:any,row:any)=>void}){const[draft,setDraft]=useState({...research});const fields=[["Industry","industry"],["Company type","companyType"],["Category","category"],["Products & services","productsServices"],["Tech focus","techFocus"],["Background","companyBackground"],["Why relevant","whyRelevantToOm"],["Resume angle","recommendedResumeAngle"]];return <Modal title={`${row.companyName} research`} onClose={onClose}><div className="grid gap-4 sm:grid-cols-2">{fields.map(([label,key])=><div key={key} className={key==="companyBackground"||key==="whyRelevantToOm"?"sm:col-span-2":""}><label className="label">{label}</label><textarea className="input min-h-24" value={draft[key]||""} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></div>)}</div><div className="mt-5 flex items-center justify-between"><span className="text-sm text-gray-500">Confidence: {research.confidenceScore}% · Sources: {(research.sources||[]).length}</span><Button onClick={()=>onSave(draft,row)} disabled={busy==="researchEdit"}>{busy==="researchEdit"?<Spinner/>:<Check size={16}/>} Save & resolve review</Button></div><h3 className="mt-6 font-bold">Verified sources</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-blue-600">{(research.sources||[]).map((s:string)=><li key={s}><a href={s} target="_blank">{s}</a></li>)}</ul></Modal>}
